### ISSUE TITLE
App closes after profile selection.

### ISSUE THREAD

**Issue by chrisaverage** [SaschaWillems/glCapsViewer#3]
The 1.0beta app starts, shows an OpenGL profile selection popup and closes immediately after clicking ok. Selecting any of the profiles has no impact. No additional info is provided (like an error message or crash handler), it just closes.

The OS is Windows 8.1. The graphics card supports OpenGL and the latest NVidia drivers (347.88) are installed. Previous version of glCapsViewer works and detects OpenGL 4.5 profile correctly.

**Comment by SaschaWillems** [comment]
I noticed that problem when selecting an OpenGL ES 1.0 profile on some NVidia devices, but never seen it happen with all profiles yet. Though I sadly don't have access to a NVidia GPU currently.

I'll add some error output for the next version, maybe that'll tell me more about why it happens. I guess it's because glfw isn't able to create a window, have had this happening on Mac OSX too, where the old CapsViewer works fine.

Thanks for letting me know!

**Comment by chrisaverage** [comment]
Curiously enough it works fine when I downloaded the source and compiled myself. Maybe it's just a deployment issue.
Compiled in x64 configuration with Qt 5.4.1, GLEW 1.12.0, GLFW 3.1.1 and boost 1.51.0.

**Comment by SaschaWillems** [comment]
Sounds great. Thanks for the feedback! I'll add some error checking though and will release a new binary soon with all libraries up-to-date. 

The problems may be caused by using an older glfw version (last binary uses 3.0.4).
